# Generated by Django 2.0.13 on 2023-01-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymoviereviews', '0002_auto_20230113_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='price',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='jangre',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='review',
        ),
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.CharField(default='', max_length=200),
        ),
    ]
